name: CD Pipeline

on: 
  push:
    branches:
      - master

jobs:     
  job_1:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup Java JDK
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 1.8
          
    - name: Build APK
      run: bash ./gradlew assembleRelease
      
    - name: Signing Android Release
      id: sign-app
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: ${{ steps.sign-app.outputs.signedReleaseFile }}
        
  job_2:
    name: Deployment
    runs-on: ubuntu-latest
    needs: job_1
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Download Artifacts
      uses: actions/download-artifact@v2
      with:
        name: app # Downloaded to the current directory
         
    - name: Upload to Play Store
      uses: r0adkll/upload-google-play@v1.0.4
      with:
        serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT }}
        packageName: com.ctext
        releaseFile: app-release-unsigned-signed.apk
        track: alpha
        userFraction: 0.05 # Portion of users who should get the staged version of the app. Accepts values between 0.0 and 1.0 (exclusive-exclusive)
        # whatsNewDirectory: /distribution/whatsnew # release notes for whats new page
        # mappingFile: /app/build/outputs/mapping/release/mapping.txt
        
  job_3:
    name: Artifactory Cleanup
    runs-on: ubuntu-latest
    steps:
    - name: Clean up
      uses: glassechidna/artifact-cleaner@master
      with:
        minimumAge: 86400 # All artifacts at least one day old