name: CD Pipeline

on: 
  push:
    branches:
      - master

jobs:

  job_1:
    name: Versioning
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        # Fetches entire history, so we can analyze commits since last tag
        fetch-depth: 0

    - name: Bump Version and Push Tag
      uses: mathieudutour/github-tag-action@v4.5
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
     
  job_2:
    name: Build
    runs-on: ubuntu-latest
    needs: job_1
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup Java JDK
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 1.8
          
    - name: Decode Keystore
      run: echo ${{ secrets.SIGNING_KEY }} | base64 --decode > my.keystore
      
    - name: Compute Version Name
      run: echo "::set-env name=VERSION_NAME::$(git describe --tags --always)"
      
    - name: Build & Signing APK
      run: bash ./gradlew bundleRelease
           -PversCode=${{ github.run_number }}
           -PversName=${{ env.VERSION_NAME }}
           -Pandroid.injected.signing.store.file=$(pwd)/my.keystore 
           -Pandroid.injected.signing.store.password=${{ secrets.KEY_PASSWORD }} 
           -Pandroid.injected.signing.key.alias=${{ secrets.ALIAS }} 
           -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }} 
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: app/build/outputs/bundle/release/app-release.aab
       
  job_3:
    name: Deployment
    runs-on: ubuntu-latest
    needs: job_2
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Download Artifacts
      uses: actions/download-artifact@v2
      with:
        name: app # Downloaded to the current directory
    
    - name: Upload to Play Store
      uses: r0adkll/upload-google-play@v1.0.4
      with:
        serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT }}
        packageName: com.seetext
        releaseFile: app-release.aab
        track: alpha
        userFraction: 0.05 # Portion of users who should get the staged version of the app. Accepts values between 0.0 and 1.0 (exclusive-exclusive)
        whatsNewDirectory: whatsnew # Release notes for whats new page
        
  job_4:
    name: Artifactory Cleanup
    runs-on: ubuntu-latest
    steps:
    - name: Clean up
      uses: glassechidna/artifact-cleaner@master
      with:
        minimumAge: 86400 # All artifacts at least one day old